name: colegio_bnnm
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.3.4 <4.0.0"
#-- PACKAGES --#
dependencies:
  connectivity_plus: ^2.3.0
  date_format: ^2.0.7
  datetime_picker_formfield_new: ^2.1.0
  flutter:
    sdk: flutter
  flutter_native_splash: 2.4.0
  get: ^4.6.6
  get_storage: ^2.1.1
  go_router: ^14.2.2
  html: ^0.15.0
  http: ^1.2.2
  http_parser: ^4.0.0
  image_picker: ^1.0.0
  intl: ^0.19.0
  logger: ^2.4.0
  lottie: ^3.1.2
  mime: ^1.0.6
  path: ^1.9.0
  provider: ^6.1.2
  smooth_page_indicator: ^1.2.0+3
  url_launcher: ^6.3.0
  web_socket_channel: ^3.0.1

flutter:
  uses-material-design: true
  #-- LOCAL ASSETS -- #
  assets:
    - assets/
    # - assets/logos
    # - assets/icons/brands
    - assets/images/
    - assets/images/on_boarding_images/
    - assets/images/lotties/
  #-- LOCAL FONTS -- #
dev_dependencies:
  flutter_lints: ^3.0.0
  flutter_test:
    sdk: flutter
